const List<String> regions = [
  "Alsace",
  "Aquitaine",
  "Auvergne",
  "Bourgogne",
  "Bretagne",
  "Centre-Val de Loire",
  "Champagne-Ardenne",
  "Corse",
  "Côte d'Azur",
  "Franche-Comté",
  "Guadeloupe",
  "Guyane",
  "Île-de-France",
  "Languedoc",
  "Limousin",
  "Lorraine",
  "Martinique",
  "Mayotte",
  "Midi-Pyrénées",
  "Nord-Pas-de-Calais",
  "Normandie",
  "Nouvelle Calédonie",
  "Pays de la Loire",
  "Picardie",
  "Poitou-Charentes",
  "Provence",
  "Réunion",
  "Rhone-Alpes",
  "Roussillon",
  "Tahiti"
];
